import httpx
import asyncio
import json
from datetime import datetime

KEY = os.getenv("GROQ_API_KEY", "your_groq_api_key_here")
MODEL = "llama-3.3-70b-versatile"

async def ask(role, prompt, max_tokens=2000):
    print(f"  Asking {role}...")
    async with httpx.AsyncClient(timeout=60) as c:
        r = await c.post(
            "https://api.groq.com/openai/v1/chat/completions",
            headers={"Authorization": f"Bearer {KEY}", "Content-Type": "application/json"},
            json={"model": MODEL, "messages": [{"role": "user", "content": prompt}], "temperature": 0.7, "max_tokens": max_tokens},
        )
        if r.status_code == 200:
            data = r.json()
            content = data["choices"][0]["message"]["content"]
            tokens = data.get("usage", {}).get("total_tokens", 0)
            print(f"  {role} responded ({tokens} tokens)")
            return content
        else:
            print(f"  {role} FAILED: {r.status_code} {r.text[:200]}")
            return f"Error: {r.status_code}"

async def main():
    print("=" * 60)
    print("MARKLY v2.0.0 - BUSINESS RESEARCH (Groq)")
    print("=" * 60)

    sections = {}

    print("\n[1/7] CEO: Strategy")
    sections["ceo_strategy"] = await ask("CEO",
        "Define research strategy to find top 5 most profitable business opportunities "
        "in India 2026 under Rs.50,000. Focus on digital/online businesses automatable "
        "with AI. Return JSON with strategy, target_sectors (5), evaluation_criteria.")

    print("\n[2/7] CAO: Market Analysis")
    sections["cao_market"] = await ask("CAO",
        "Analyze Indian digital business landscape 2026. Top 5 opportunities for solo "
        "entrepreneurs: 1)KDP Publishing 2)Affiliate Marketing 3)SaaS Micro-products "
        "4)YouTube Automation 5)AI Consulting. For each: name, description, "
        "monthly_revenue_inr, startup_cost_inr, difficulty_1_10, time_to_revenue_days, "
        "scalability_1_10, competition_level. Return JSON.")

    print("\n[3/7] Research: Deep Dive")
    sections["research_deep"] = await ask("Research",
        "Deep research on 5 online businesses in India 2026: KDP Publishing, Affiliate "
        "Marketing, SaaS Micro-products, YouTube Automation, AI Consulting. For each: "
        "market size, underserved niches, step-by-step setup, tools needed, timeline to "
        "profitability, income after 3 and 12 months, risks and mitigation. Return JSON.",
        max_tokens=4096)

    print("\n[4/7] CFO: Financials")
    sections["cfo_financials"] = await ask("CFO",
        "Financial projections for 5 online businesses in India with Rs.50,000 budget. "
        "For each: investment breakdown, monthly costs, break-even timeline, conservative "
        "revenue months 1-12, optimistic revenue, ROI after 12 months, GST/tax implications. "
        "Return JSON.", max_tokens=4096)

    print("\n[5/7] CTO: Technical")
    sections["cto_technical"] = await ask("CTO",
        "Technical guide for 5 AI-automated online businesses. For each: tech stack "
        "(free/cheap), automation with AI, APIs needed, hosting costs, security, how AI "
        "agents automate daily ops, Day 1-30 setup plan. Return JSON.", max_tokens=4096)

    print("\n[6/7] CMO: Marketing")
    sections["cmo_marketing"] = await ask("CMO",
        "Marketing strategy for 5 online businesses in India. For each: target audience, "
        "top 3 channels, content strategy, SEO keywords, social media plan, acquisition "
        "cost, AI for content, 90-day marketing plan. Return JSON.", max_tokens=4096)

    print("\n[7/7] CEO: Final Recommendation")
    sections["ceo_final"] = await ask("CEO",
        "FINAL RECOMMENDATION. Rank 5 businesses best to worst. Score each 0-100. "
        "Recommend which 2-3 to start FIRST. 30-day action plan with daily tasks. "
        "Expected monthly income after 3, 6, 12 months. Minimum budget and allocation. "
        "Top 3 risks and handling. Make it actionable. Return JSON.", max_tokens=4096)

    # Generate report
    print("\n" + "=" * 60)
    print("Generating report...")
    print("=" * 60)

    path = "D:\\agent company\\business_research_report.md"
    now = datetime.now().isoformat()

    with open(path, "w", encoding="utf-8") as f:
        f.write("# Markly v2.0.0 - Business Opportunity Research Report\n\n")
        f.write(f"**Generated:** {now}\n")
        f.write(f"**System:** Markly AI Business Platform v2.0.0\n")
        f.write(f"**Agents:** CEO, CAO, Research, CFO, CTO, CMO (6 C-Suite agents)\n")
        f.write(f"**LLM:** Groq llama-3.1-70b-versatile\n\n")
        f.write("---\n\n")

        f.write("## Executive Summary\n\n")
        f.write("This report was generated by Markly's autonomous C-Suite agent team using "
                "real-time LLM analysis via Groq API. 6 AI agents researched, analyzed, "
                "and recommended the best business opportunities to start in India in 2026 "
                "with Rs.50,000 budget.\n\n")
        f.write("The research covered 5 business categories:\n")
        f.write("1. Amazon KDP Publishing\n2. Affiliate Marketing\n3. SaaS Micro-products\n")
        f.write("4. YouTube/Content Automation\n5. AI Consulting Services\n\n")
        f.write("---\n\n")

        titles = {
            "ceo_strategy": "1. CEO - Research Strategy",
            "cao_market": "2. CAO - Market Analysis",
            "research_deep": "3. Research - Deep Dive Analysis",
            "cfo_financials": "4. CFO - Financial Projections",
            "cto_technical": "5. CTO - Technical Implementation",
            "cmo_marketing": "6. CMO - Marketing Strategy",
            "ceo_final": "7. CEO - Final Recommendation",
        }

        for key, title in titles.items():
            f.write(f"## {title}\n\n")
            content = sections.get(key, "No response")
            if content.startswith("```"):
                lines = content.split("\n")
                if lines[0].startswith("```"):
                    lines = lines[1:]
                if lines and lines[-1].strip() == "```":
                    lines = lines[:-1]
                content = "\n".join(lines)
            f.write(content)
            f.write("\n\n---\n\n")

        f.write("## Disclaimer\n\n")
        f.write("Generated by AI agents using LLM analysis. Financial projections are estimates. "
                "Verify with real-world data. Consult a financial advisor before investing.\n")

    print(f"\nReport saved: {path}")
    print("DONE!")

asyncio.run(main())
